name: air_reservation
description: A new Flutter project for air ticket reservation.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.20
  hugeicons: ^0.0.7
  http: ^1.2.2
  intl: ^0.18.0

  english_words: ^4.0.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/logo.jpg
    - assets/airlines_logo/
    - assets/segment_line.png

  fonts:
    - family: HgiStrokeRounded
      fonts:
        - asset: lib/fonts/hgi-stroke-rounded.ttf
  uses-material-design: true